### ISSUE TITLE
So, I have Sith Jet Trooper morphs, that can ALSO be used for a whole new division, you just have to recolor them. The whole new division part doesn't matter right now, I just need the morphs to get added into the ST part. If you have an already scripted jetpack, then that'll go great with it too. So, what I have are the Scrim Team morphs and the Lamda-12 morphs. Note, these are all ST. I'll send pictures once you DM me back.     orange.#5138       (  

### ISSUE THREAD

**Issue by theorangestat99** [ThanatosFernandez/TFODev#13]
**What is your discord tag**
Please place your discord tag E.G: Testuser#5472

**What would you like to suggest**
What is your suggestion on how to improve something up?

**Reference**
Post a screenshot/Video for us to have clear understanding.

**Additional comments**
If there's something more to what you're suggesting, tell us!

**Comment by ThanatosFernandez** [comment]
Please reply to my DMs when possible.
