### ISSUE TITLE
Minor Fixes for the MT Commanding Officer Morph

### ISSUE THREAD

**Issue by XayDevelopmentStudios** [ThanatosFernandez/TFODev#14]
**What is your discord tag**
Please place your discord tag E.G: Testuser#5472
xay#3660
**Describe the bug**
1 - People with the CO rank get two sets of tools at SKB. (Not urgent to fix)
2 - The speed tool is seemingly broken only for the CO, but not other MT ranks. 
**Expected behavior**
A clear and concise description of what you expected to happen instead what's going on now.
The speed tool should increase speed when used but does nothing for the CO rank. 
**Evidence**
If applicable, add screenshots/videos to help explain your problem.
N/A
**Additional context**

**Comment by ThanatosFernandez** [comment]
1. Tool dupe fixed
2. Speed can not be fixed I believe due to there are heavy weapons which slow people down anyway, just like when RT had ET axes
