### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vidudrox** [ThanatosFernandez/TFODev#18]
**What is your discord tag**
Please place your discord tag E.G: Testuser#5472
Vidudrox#0575
**Describe the bug**
(Sometimes) When swinging and unigniting the HG Vibrostaff, it has either a smaller or larger delay.
**Expected behavior**
A clear and concise description of what you expected to happen instead what's going on now.
When swinging, igniting, or unigniting, it is supposed to happen instantly.
**Evidence**
If applicable, add screenshots/videos to help explain your problem.
N/A
**Additional context**
N/A

**Comment by ThanatosFernandez** [comment]
Adjusted speed on the animation speed, hopefully it fixes the issue with lag.
