### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SlrNexus** [ThanatosFernandez/TFODev#2]
**Describe the bug**
So basically, with the minigun (gamepass) when you move around ect, or even just stand still It will go into a slop, like this. 
![image](https://user-images.githubusercontent.com/64013122/79746242-8e126e80-8301-11ea-8aaf-d4b377aa72df.png) when you fire, it cannot go forward as it is glitched down, so it is useless at that point.

**Expected behavior**
A clear and concise description of what you expected to happen instead what's going on now.
It is meant to stick up, always like this. 
![image](https://user-images.githubusercontent.com/64013122/79746318-b1d5b480-8301-11ea-94d5-9ba0a1e46f62.png)

**Evidence**
If applicable, add screenshots/videos to help explain your problem.

**Additional context**

**Comment by ThanatosFernandez** [comment]
Will take a look what could be done to it, thank you for the report!
