### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by HunikPL** [ThanatosFernandez/TFODev#24]
**What is your discord tag**
Ze Wo#0581

**What would you like to suggest**
Make the arrest time for clearance 3 ( TK itc.)
Shorter around 600-1000 seconds to give them another chance

**Reference**
Not needed as now the arrest time is 9999999999 and you made it.

**Additional comments**
N/A

**Comment by ThanatosFernandez** [comment]
Reasonable, I will add one more in the middle section with 600 seconds time.

**Comment by ThanatosFernandez** [comment]
Added in "TK of personnel" 
![image](https://user-images.githubusercontent.com/64010566/80413691-88f08900-88d8-11ea-894a-7a903e192192.png)
