### ISSUE TITLE
[REQUEST] add a button so we can open/close the HG hanger

### ISSUE THREAD

**Issue by Lordwolfzy** [ThanatosFernandez/TFODev#25]
**What is your discord tag**
Lord_wolfzy#6644

**What would you like to suggest**
Add something like the navy hanger so we can close down the hanger and Remove the top entrance and the Metal bar inside the HG hanger.
Add an id group seat only so that if you're not in HG or FOR you will get killed.

**Reference**
![image](https://user-images.githubusercontent.com/64015916/80399599-ae36c480-88e3-11ea-83f3-76acc10f5bd3.png)
![image](https://user-images.githubusercontent.com/64015916/80399633-b7c02c80-88e3-11ea-8f30-e5e22c0e4335.png)

**Additional comments**
None

**Comment by ThanatosFernandez** [comment]
Added a panel where it can be activated from: 
![image](https://user-images.githubusercontent.com/64010566/80413163-affa8b00-88d7-11ea-942c-55e97cceda5c.png)
