### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by HunikPL** [ThanatosFernandez/TFODev#3]
I would suggest giving tazer to Ion PL SL and CC (RT division) 
![20200420_134306](https://user-images.githubusercontent.com/64013480/79748098-23673000-830d-11ea-95bb-47f8b5609fe5.jpg) Ion PL tools some tools are officer tools. Love you no homo.

**Comment by ThanatosFernandez** [comment]
The current tools are given exclusively by names, so I'd need you to make a list of people who needs them.

**Comment by HunikPL** [comment]
Usernames: HunikPL, Fyrdracca, ripclaw2b, camjay74, Palacsinta_22
You can check RT discord.

**Comment by ThanatosFernandez** [comment]
> Usernames: HunikPL, Fyrdracca, ripclaw2b, camjay74, Palacsinta_22
> You can check RT discord.

Adding rn
