### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FOR-OP3** [ThanatosFernandez/TFODev#31]
**What is your discord tag**
Please place your discord tag E.G: Testuser#5472
nut#9669
**Describe the bug**
2 of my operatives, plusospre and PhantomVezerict have ST jet trooper morphs that need to be unscripted from them.
**Expected behavior**
A clear and concise description of what you expected to happen instead what's going on now.
It should give my operatives Raider armor, instead of the scripted morph
**Evidence**
If applicable, add screenshots/videos to help explain your problem.
![image](https://user-images.githubusercontent.com/64348618/81712988-e9380c80-943a-11ea-9de8-43c7fc8757ce.png)

**Additional context**
N/A

**Comment by ThanatosFernandez** [comment]
Dm me on discord because I can't find you.
