### ISSUE TITLE
 I need my Eclipse CC Morph scripted to myself.

### ISSUE THREAD

**Issue by whitedwarf17** [ThanatosFernandez/TFODev#33]
**What is your discord tag**
Please place your discord tag E.G: Testuser#5472

**What would you like to suggest**
What is your suggestion on how to improve something up?

**Reference**
Post a screenshot/Video for us to have clear understanding.

**Additional comments**
If there's something more to what you're suggesting, tell us!

**Comment by whitedwarf17** [comment]
What is your discord tag
ChronicCappy#9930

What would you like to suggest
I would like my morph scripted to me. My name is ChronicalzBTW. It's for the Eclipse Company of the Executioner Troopers. 

Reference
https://cdn.discordapp.com/attachments/697101403923021926/710521218209546240/unknown.png

Additional comments
I am filling this out for ChronicalzBTW because he had no idea what he was doing.

**Comment by ThanatosFernandez** [comment]
I think I've done it today. If not, please contact me again!
