### ISSUE TITLE
[REQUEST] Move the Hanger

### ISSUE THREAD

**Issue by Lordwolfzy** [ThanatosFernandez/TFODev#35]
**What is your discord tag**
Lord_Wolfzy

**What would you like to suggest**
Moving the hanger to the front of the base, Also redoing some of the front interiors

**Reference**

![image](https://user-images.githubusercontent.com/64015916/82161549-f6844980-98c7-11ea-870a-a4b767b2882a.png)

**Additional comments**
If there's something more to what you're suggesting, tell us!

**Comment by ThanatosFernandez** [comment]
Since I'm only a coder, you'll need to contact some other person for that.
