### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Londony100** [ThanatosFernandez/TFODev#36]
**What is your discord tag**
Please place your discord tag E.G: Londony100#8748

**Describe the bug**
FOR can't open the Throne room hangar

**Expected behavior**
FOR should be able to open up the Throne room Hangar door

**Evidence**
If you want, we can go to SKB and I can show you.

**Additional context**

**Comment by ThanatosFernandez** [comment]
Fixed, forgot to close the ticket.
