### ISSUE TITLE
[REQUEST] HG New Place

### ISSUE THREAD

**Issue by Lordwolfzy** [ThanatosFernandez/TFODev#37]
**What is your discord tag**
Lord_Wolfzy#6644

**What would you like to suggest**
Requesting HG morphs to be added to the new place.

**Reference**
https://www.roblox.com/games/5044860056/Honor-Guard-Training-Ground

**Additional comments**
If there's something more to what you're suggesting, tell us!

**Comment by ThanatosFernandez** [comment]
Don't have access to such place.
