### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by Londony100** [ThanatosFernandez/TFODev#38]
**What is your discord tag**
Please place your discord tag E.G: Londony100#8748

**What would you like to suggest**
So for the FOR knifes, they sound like light sabers... I think I'd be better if it had the old sound.
**Reference**
It's the old FOR melee sound.
**Additional comments**
If there's something more to what you're suggesting, tell us!

**Comment by ThanatosFernandez** [comment]
Unfortunately the old sounds are gone.
