### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by fishywalrus1** [ThanatosFernandez/TFODev#39]
**What is your discord tag**
fishy#1873

**What would you like to suggest**
Script the ST jetpacks to fishywalrus, Commander_Pow, wildstyle0508 and blackcrops

**Reference**
Post a screenshot/Video for us to have clear understanding.

**Additional comments**
If there's something more to what you're suggesting, tell us!

**Comment by ThanatosFernandez** [comment]
I've tested it and unfortunately it won't work like that, due to it must be attached to each morph individually. Since everyone has their morph from different division or etc, it can't be done.
