### ISSUE TITLE
Addition of Prye Morph and MT Tools

### ISSUE THREAD

**Issue by XayDevelopmentStudios** [ThanatosFernandez/TFODev#5]
**What is your discord tag**
Please place your discord tag E.G: Testuser#5472
fishy#1873
**What would you like to suggest**
What is your suggestion on how to improve something up?
1, Please add the Commander Prye morph to fishywalrus (ID:587543109)
2, Please add the RT Speed Tool to the MT Group (ID:5192342)
3, Please add a RT style Shield (preferably black) to Epsilon Squad and XO+ (ID: 5192342:45, 5192342:70, 5192342:100)
**Reference**
Post a screenshot/Video for us to have clear understanding.
N/A
**Additional comments**
If there's something more to what you're suggesting, tell us!
Thank you!

**Comment by ThanatosFernandez** [comment]
- [x] Added Pyre morph
